### ISSUE TITLE
EventBridge not enabled on FileReceiverBucket

### ISSUE THREAD

**Issue by hnammala1** [aws-samples/event-driven-architecture-using-s3-event-notifications#3]
I got an error when deploying the stack:
Properties validation failed for resource FileReceiverBucket with message: #/NotificationConfiguration/EventBridgeConfiguration: required key [EventBridgeEnabled] not found

**Comment by vsbatista** [comment]
Can you please pull the latest version and double check? I have checked in a fix for that a few days ago.

**Comment by vsbatista** [comment]
Resolved by https://github.com/aws-samples/event-driven-arch-eventbridge-lambda/commit/b5ce1aaf4b26266883553851e6dd03842e27d1ff
