### ISSUE TITLE
Suggestion: GitHub readme for pre-requisite information

### ISSUE THREAD

**Issue by hnammala1** [aws-samples/event-driven-architecture-using-s3-event-notifications#4]
I think we should add the pre-requisite information in the GitHub readme. The readme only mentions to install SAM CLI, AWS CLI and docker as pre-reqs but does not provide the download links/instructions explicitly. So, I think, adding those links and instructions would help the users to successfully implement the github solution

**Comment by vsbatista** [comment]
Pre-requisite is on the end of README, as per SAM standard template. However, I'll move that section up and include a docker link. Other tools(SAM, CLI) are already documented.

**Comment by vsbatista** [comment]
Closed by 2cd07c55b62245b21392f3aa158dfba07d44f314
